name: Build
on: [push]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: sudo apt-get install -y libproj-dev
      - name: make config-linux
        run: make config-linux
      - name: make therion
        run: make therion
  macos:
    name: Build on macOS
    runs-on: macOS-latest
    steps:
        - uses: actions/checkout@v1
        - name: install dependencies
          run: brew install pkg-config proj
        - name: make config-macosx
          run: make config-macosx
        - name: make therion
          run: make therion
